#%RAML 1.0
baseUri: http://test:8081
title: Songs
/songs:
  get:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
  post:
    body:
      application/json:
    responses:
          200:
            body:
              application/json:
  put:
    body:
     application/json:
    responses:
      200:
        body:
          application/json:
  delete:
    body:
     application/json:
    responses:
        200:
          body:
            application/json:
/users:
  get:
    body:
     application/json:
    responses:
      200:
        body:
          application/json:
  post:
    body:
      application/json:
    responses:
       200:
        body:
          application/json:
  put:
      body:
        application/json:
      responses:
        200:
          body:
            application/json: